---
- hosts: all
  gather_facts: false
  tasks:
    - name: espera ssh
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 60
      vars:
        ansible_user: ec2-user

- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Intalando Docker
      become: true
      shell: "amazon-linux-extras install docker -y"
    - name: Add ec2-user to group docker
      become: true
      ansible.builtin.user:
        name: ec2-user
        groups: docker
    - name: Install Docker Compose
      pip:
        name: docker-compose
        executable: pip3
    - name: Enabled doker
      become: true
      service:
        name: docker
        state: started
        enabled: yes
    - name: Copy docke yml to directory
      become: true
      copy:
        src: /home/sinensia/hello-JATaws/docker-compose.yml
        dest: /home/ec2-user
        owner: ec2-user
        group: ec2-user
        mode: "0644"
        directory_mode: "0755"
    - name: Bring image
      command: docker pull ghcr.io/albertosantiago-lt/hello-2048/hello2048:latest
    - name: Execute docker-compose up
      ansible.builtin.shell: docker-compose up -d
      args:
        chdir: /home/ec2-user
