---
- hosts: all
  gather_facts: false
  tasks:
    - name: espera ssh
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 60
      vars:
        ansible_user: ec2-user

- hosts: all
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Intalando Docker
      become: true
      shell: "amazon-linux-extras install docker -y"

    - name: Enabled doker
      become: true
      service:
        name: docker
        state: started
        enabled: yes
