---
- hosts: all
  gather_facts: false
  tasks:
    - name: espera ssh
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user

- hosts: all
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Intalando Apache Https
      ansible.builtin.shell:
       cmd: sudo amazon-linux-extras install docker
    - name: Enabled doker
      service:
        name: docker
        enabled: true
        state: started
